# Generated by Django 2.2.7 on 2019-12-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20191129_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question_order',
        ),
        migrations.AddField(
            model_name='question',
            name='position_in_test',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
