# Generated by Django 2.2.7 on 2019-12-05 22:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20191205_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('CH', 'CHOICE'), ('MU', 'CHOICE_MULT'), ('VA', 'VALUE'), ('TE', 'TEXT')], default='CH', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_variants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer_variants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
    ]
