# Generated by Django 2.2.7 on 2019-12-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20191206_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_type',
            new_name='answerType',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_variants',
            new_name='answerVariants',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer_variants',
            new_name='correctAnswerVariants',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='position_in_test',
            new_name='positionInTest',
        ),
    ]
