# Generated by Django 2.1.7 on 2019-12-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20191206_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantName', models.CharField(max_length=30)),
                ('timeInSeconds', models.IntegerField()),
                ('finishTime', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.Test')),
            ],
        ),
    ]
