# Generated by Django 2.1.7 on 2019-12-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='testResult',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.TestResult'),
        ),
    ]
