# Generated by Django 2.1.7 on 2019-12-12 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_questionanswer_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 20, 27, 7, 810779)),
        ),
    ]
