# Generated by Django 2.0.7 on 2019-12-26 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20191222_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 17, 47, 16, 750572)),
        ),
    ]
