# Generated by Django 2.1.7 on 2020-03-06 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20200306_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='correctAnswerValue',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correctAnswerVariants',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answerVariants',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 10, 8, 29, 610365)),
        ),
        migrations.AddField(
            model_name='question',
            name='answerVariants',
            field=models.ManyToManyField(blank=True, null=True, to='tests.AnswerVariant'),
        ),
    ]
