# Generated by Django 2.1.7 on 2020-03-06 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_auto_20200306_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answerVariants',
        ),
        migrations.AddField(
            model_name='answervariant',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Question'),
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Question'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 10, 29, 36, 653891)),
        ),
    ]
