# Generated by Django 2.1.7 on 2020-03-06 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20200306_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='answerText',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 10, 40, 41, 344580)),
        ),
    ]
