# Generated by Django 2.1.7 on 2020-03-06 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_auto_20200306_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='displayPattern',
            field=models.CharField(blank=True, choices=[('1', 'VERTICAL_TEXT_PICTURE'), ('2', 'VERTICAL_PICTURE_TEXT'), ('3', 'HORIZONTAL_TEXT_PICTURE'), ('4', 'HORIZONTAL_PICTURE_TEXT')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 11, 3, 27, 811548)),
        ),
    ]
