# Generated by Django 2.1.7 on 2020-03-06 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_auto_20200306_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerType',
            field=models.CharField(blank=True, choices=[('CH', 'CHOICE'), ('MU', 'CHOICE_MULT'), ('VA', 'VALUE'), ('TE', 'TEXT')], default='TE', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 14, 44, 46, 522473)),
        ),
    ]
