# Generated by Django 2.1.7 on 2020-03-06 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_auto_20200306_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 14, 56, 21, 418532)),
        ),
    ]
