# Generated by Django 3.0.4 on 2020-05-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_auto_20200408_2348'),
        ('tests', '0024_auto_20200306_1456'),
    ]

    operations = [
    ]
