# Generated by Django 3.0.4 on 2020-05-05 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0025_merge_20200505_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('1', 'STUDENT'), ('2', 'WORKER'), ('3', 'ADMIN')], default='1', max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 11, 28, 24, 570791)),
        ),
    ]
