# Generated by Django 3.0.6 on 2020-05-14 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_auto_20200505_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 23, 51, 51, 183247)),
        ),
    ]
