# Generated by Django 3.0.6 on 2020-05-19 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_auto_20200514_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='participantName',
            new_name='participantLogin',
        ),
        migrations.AddField(
            model_name='moduleuser',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='moduleuser',
            name='group',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 5, 44, 37, 953807)),
        ),
    ]
