# Generated by Django 3.0.6 on 2020-05-19 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_auto_20200519_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='participantLogin',
            new_name='participantName',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='finishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 5, 45, 59, 885253)),
        ),
    ]
